# Generated by Django 5.0.4 on 2024-05-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_question_answer_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='answers',
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='quiz_answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_answers', to='users.customuser'),
        ),
    ]
