# Generated by Django 5.0.4 on 2024-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_answers_alter_question_answer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_info',
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='answer',
            field=models.TextField(max_length=1500),
        ),
    ]
