# Generated by Django 5.0.4 on 2024-05-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('MultipleChoice', 'Выбор нескольких вариантов'), ('Choice', 'Выбор одного варианта')], default='Choice', max_length=15),
            preserve_default=False,
        ),
    ]
