# Generated by Django 5.0.4 on 2024-05-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_quiz_type'),
        ('users', '0005_alter_customuser_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='depends_questions', to='questionnaire.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choices',
            field=models.ManyToManyField(related_name='quizzes', to='questionnaire.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='depends_quizzes', to='questionnaire.answer'),
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_question', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='questionnaire.answer')),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_quiz', to='users.customuser')),
            ],
        ),
    ]
