# Generated by Django 5.0.4 on 2024-05-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_question_depends_on_alter_quiz_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairequestion',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questionnairequestion',
            old_name='quiz',
            new_name='question',
        ),
    ]
