# Generated by Django 5.0.4 on 2024-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_remove_questionnairequiz_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MultipleChoice', 'Выбор нескольких вариантов'), ('Choice', 'Выбор одного варианта')], default=('MultipleChoice', 'Выбор нескольких вариантов'), max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('Long', 'Развернутый ответ'), ('Short', 'Краткий ответ')], max_length=15),
        ),
    ]
