# Generated by Django 5.0.4 on 2024-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Long', 'Развернутый ответ'), ('Short', 'Краткий ответ')], max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('MultipleChoice', 'Выбор нескольких вариантов'), ('Choice', 'Выбор одного варианта')], max_length=15),
        ),
    ]
