# Generated by Django 5.0.4 on 2024-05-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_alter_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='index_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='index_num',
            field=models.IntegerField(default=1),
        ),
    ]
