# Generated by Django 5.0.4 on 2024-05-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_question_index_num_quiz_index_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='index_num',
            field=models.IntegerField(),
        ),
    ]
